# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26444f50de94d17e40bfb9d895e1236bd88ec69188ba076280ca0c67ffb8281adec9d32516ee848a2e5d3745bec9e2313673e71a6ff86b1bc3b3721586f41138

test:
  secret_key_base: 00a7f911d1cac43692a99e2924a83ee373625ecf9bafed2145b8d231648d5de08984a28c1f09a053c98d01f5fb44e3d77eee1c0c4b92a9c540b83f8a75cfad80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
